DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS mpaas CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS films_genres CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    CONSTRAINT uniq_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL,
    registration_date TIMESTAMP WITHOUT TIME ZONE,
    dtype VARCHAR,
    role_id BIGINT NOT NULL,
    password VARCHAR NOT NULL,
    overlord BOOLEAN NOT NULL,
    CONSTRAINT uniq_email UNIQUE (email),
    CONSTRAINT roles_table_fk foreign key (role_id) references roles

);

CREATE TABLE IF NOT EXISTS genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    CONSTRAINT genre_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS mpaas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    CONSTRAINT mpaa_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    duration INTEGER NOT NULL,
    country VARCHAR,
    release_date TIMESTAMP WITHOUT TIME ZONE,
    author VARCHAR NOT NULL,
	mpaa_id BIGINT NOT NULL,
	CONSTRAINT mpaa_table_fk foreign key (mpaa_id) references mpaas
);

CREATE TABLE IF NOT EXISTS films_genres (
    genres_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    CONSTRAINT film_genre_pk primary key (genres_id, film_id),
    CONSTRAINT genre_table_fk foreign key (genres_id) references genres,
    CONSTRAINT film_table_fk foreign key (film_id) references films
);